### PR TITLE
Consider datafield 209R$4 for mods:identifier[@type ='url'] #105

### PR DESCRIPTION
**Pull request by Possommi**

### CODE REVIEW

**Comment by rsteph-de** [comment]
It is not that simple !!!
209R is a library specific field and contains the URL to the resource as it it licensed by the institution. This may be another platform or repository  as specified in field 017C. Or the URL may be enriched with parameters to specify the institution that has licensed the resource.

In practice 99% of the values in this field are copies from one of the URLs in 017C.
That means that at least we need to check for duplicate entries with 017C or skip this PR completely.

Please provide a PPN as an example.

**Comment by Possommi** [comment]
> It is not that simple !!! 209R is a library specific field and contains the URL to the resource as it it licensed by the institution. This may be another platform or repository as specified in field 017C. Or the URL may be enriched with parameters to specify the institution that has licensed the resource.
> 
> In practice 99% of the values in this field are copies from one of the URLs in 017C. That means that at least we need to check for duplicate entries with 017C or skip this PR completely.
> 
> Please provide a PPN as an example.

 [884336697](https://unapi.k10plus.de/?&format=picaxml&id=opac-de-ilm1:ppn:884336697)

**Comment by Possommi** [comment]
> > It is not that simple !!! 209R is a library specific field and contains the URL to the resource as it it licensed by the institution. This may be another platform or repository as specified in field 017C. Or the URL may be enriched with parameters to specify the institution that has licensed the resource.
> > In practice 99% of the values in this field are copies from one of the URLs in 017C. That means that at least we need to check for duplicate entries with 017C or skip this PR completely.
> > Please provide a PPN as an example.
> 
> [884336697](https://unapi.k10plus.de/?&format=picaxml&id=opac-de-ilm1:ppn:884336697)

This ppn does not have field 017C.

**Comment by kkrebs** [comment]
fixed with touchtitle directly in catalog

**Pull request closed without merging**
